extends Node

signal locale_changed(locale: String)

const DEFAULT_LOCALE := "en"
const SUPPORTED_LOCALES := ["en", "zh-CN"]

var locale: String = DEFAULT_LOCALE

var _texts := {
	"zh-CN": {
		"ui.login.username": "用户名",
		"ui.login.email": "邮箱",
		"ui.login.password": "密码",
		"ui.login.loading": "加载中...",
		"ui.login.syncing": "同步数据中...",
		"ui.player.default_name": "玩家",
		"ui.player.stats": "Lv.%d  战力 %d",
		"ui.player.level_short": "Lv.%d",
		"ui.player.combat_power_short": "%d",
		"ui.color.white": "白",
		"ui.color.green": "绿",
		"ui.color.blue": "蓝",
		"ui.color.purple": "紫",
		"ui.color.orange": "橙",
		"ui.color.black": "黑",
		"ui.color.red": "红",
		"error.draw.translating": "抽卡随机数组翻译失败",
		"error.draw.reconciling": "网络抖动，抽卡结果正在同步确认",
		"error.draw.pending": "上一次抽卡仍在确认中",
		"error.draw.no_stamina": "体力不足",
		"error.card.not_in_pool": "卡牌不在当前卡池中",
		"error.card.hand_full": "手牌槽已满",
		"error.card.invalid_hand_slot": "手牌槽位无效",
		"error.card.not_in_hand_slot": "卡牌不在此手牌槽位",
		"error.card.pool_full": "卡池已满",
		"error.synthesis.need_five": "需要恰好5张卡牌",
		"error.synthesis.duplicate": "卡牌选择不能重复",
		"error.synthesis.sync": "卡牌位置同步失败：%s",
		"ui.login.title.login": "登录",
		"ui.login.title.register": "注册",
		"ui.login.submit.login": "登录",
		"ui.login.submit.register": "注册",
		"ui.login.switch.to_register": "没有账号？注册",
		"ui.login.switch.to_login": "已有账号？登录",
		"ui.login.exit_game": "退出游戏",
		"ui.login.error.missing_username_password": "用户名和密码不能为空",
		"ui.login.error.missing_email": "邮箱不能为空",
		"ui.login.country": "国籍",
		"ui.login.country.hint": "国籍（默认：地球）",
		"ui.login.prepare.title": "登录准备",
		"ui.login.prepare.waiting": "等待开始",
		"ui.login.prepare.failed": "登录准备失败",
		"ui.login.prepare.done": "准备完成，即将进入主界面",
		"ui.login.prepare.retry": "重试",
		"ui.login.prepare.back": "返回修改账号",
		"ui.login.prepare.retry_hint": "请检查网络或账号信息后重试。失败步骤已写入本地日志。",
		"ui.login.prepare.status.pending": "待处理",
		"ui.login.prepare.status.running": "进行中",
		"ui.login.prepare.status.success": "✓ 完成",
		"ui.login.prepare.status.failed": "失败",
		"ui.login.prepare.step.init_local_config": "初始化本地配置",
		"ui.login.prepare.step.check_client_version": "检查客户端版本",
		"ui.login.prepare.step.load_local_token": "读取本地会话",
		"ui.login.prepare.step.auth_refresh_or_login": "验证或恢复账号",
		"ui.login.prepare.step.create_game_session": "建立游戏会话",
		"ui.login.prepare.step.load_player_bootstrap": "加载基础资料",
		"ui.login.prepare.step.load_today_catalog": "加载今日卡组",
		"ui.login.prepare.step.connect_realtime_or_heartbeat": "连接在线状态",
		"ui.login.prepare.step.enter_main_menu": "进入主界面",
		"ui.login.prepare.current.init_local_config": "正在初始化本地配置",
		"ui.login.prepare.current.check_client_version": "正在检查客户端版本",
		"ui.login.prepare.current.load_local_token": "正在读取本地会话",
		"ui.login.prepare.current.auth_refresh_or_login": "正在验证账号或恢复会话",
		"ui.login.prepare.current.create_game_session": "正在建立游戏会话",
		"ui.login.prepare.current.load_player_bootstrap": "正在加载玩家基础资料",
		"ui.login.prepare.current.load_today_catalog": "正在加载今日可见卡组",
		"ui.login.prepare.current.connect_realtime_or_heartbeat": "正在连接在线状态",
		"ui.login.prepare.current.enter_main_menu": "正在进入主界面",
		"ui.login.prepare.detail.session_saved": "会话已保存",
		"ui.login.prepare.detail.background": "后台继续加载",
		"ui.login.prepare.detail.no_saved_session": "本地没有可恢复会话",
		"ui.login.queue.waiting": "服务器繁忙，排队中：第 %d 位，预计 %d 秒",
		"ui.login.queue.admitted": "排队已放行，正在进入",
		"ui.login.queue.timeout": "排队等待超时，请稍后重试",
		"ui.login.loading.entering": "正在进入万象卡域",
		"ui.login.loading.collection": "正在准备收藏空间",
		"ui.login.loading.cards": "正在整理卡池与手牌",
		"ui.login.loading.online": "正在建立游戏状态",
		"ui.login.loading.done": "准备完成",
		"ui.card_pool.refresh.free": "体力抽卡",
		"ui.card_pool.refresh.free_newbie": "赠送体力 %d",
		"ui.card_pool.refresh.free_regular": "体力 %d",
		"ui.card_pool.refresh.next_free": "下次体力 %s",
		"ui.card_pool.refresh.cost_stamina": "下次花费：%d 体力",
		"ui.card_pool.refresh.cost_gold": "下次花费：%d 金币",
		"ui.card_pool.refresh.cost_gem": "下次花费：%d 宝石",
		"ui.card_pool.refresh.gold": "金币抽卡",
		"ui.card_pool.refresh.gem": "宝石抽卡",
		"ui.menu.title": "设置",
		"ui.menu.music_volume": "音乐音量",
		"ui.menu.sfx_volume": "音效音量",
		"ui.menu.mute": "🔊 静音",
		"ui.menu.muted": "🔇 已静音",
		"ui.menu.logout": "🚪 登出",
		"ui.menu.language": "语言",
		"ui.menu.resolution": "分辨率",
		"ui.menu.window_mode": "显示模式",
		"ui.menu.window_mode.fullscreen": "全屏",
		"ui.menu.window_mode.windowed": "窗口模式",
		"ui.settings.tab.basic": "基础配置",
		"ui.settings.tab.controller": "键位设置",
		"ui.settings.tab.profile": "玩家信息",
		"ui.profile.title": "玩家信息设置",
		"ui.profile.avatar": "头像",
		"ui.profile.avatar.change": "更换头像",
		"ui.profile.avatar.select": "选择已解锁头像",
		"ui.profile.region": "区域",
		"ui.profile.saving": "正在保存…",
		"ui.profile.saved": "已保存",
		"ui.profile.save_failed": "保存失败，请稍后重试",
		"ui.profile.avatar.north_star": "北极星徽章",
		"ui.profile.avatar.moon_phase": "月相徽章",
		"ui.profile.avatar.comet": "彗星徽章",
		"ui.profile.avatar.armillary": "天球仪徽章",
		"ui.profile.avatar.ostrich": "鸵鸟馆员",
		"ui.profile.avatar.camel": "骆驼档案员",
		"ui.profile.avatar.bat": "蝙蝠观测员",
		"ui.profile.avatar.lynx": "猞猁鉴定师",
		"ui.profile.avatar.magnifier": "鉴定放大镜",
		"ui.profile.avatar.seal": "馆藏封蜡章",
		"ui.profile.avatar.display_key": "展柜钥匙",
		"ui.profile.avatar.astrolabe": "星盘仪",
		"ui.controller.title": "手柄键位",
		"ui.controller.reset": "恢复默认手柄键位",
		"ui.controller.action.pointer_primary": "鼠标左键 / 激活焦点",
		"ui.controller.action.pointer_secondary": "鼠标右键",
		"ui.controller.action.nav_prev": "上一个导航页面",
		"ui.controller.action.nav_next": "下一个导航页面",
		"ui.controller.action.hand_page": "手牌翻页",
		"ui.controller.action.draw_free": "体力 / 免费抽卡",
		"ui.controller.action.synthesize": "合成",
		"ui.controller.action.store_vault": "存入保险箱",
		"ui.controller.action.discard": "丢弃",
		"ui.controller.action.draw_gem": "宝石抽卡",
		"ui.controller.action.draw_gold": "金币抽卡",
		"ui.controller.binding.r2": "R2",
		"ui.controller.binding.l2": "L2",
		"ui.controller.binding.r1": "R1",
		"ui.controller.binding.l1": "L1",
		"ui.controller.binding.a": "A",
		"ui.controller.binding.b": "B",
		"ui.controller.binding.x": "X",
		"ui.controller.binding.y": "Y",
		"ui.controller.binding.dpad_up": "十字键上",
		"ui.controller.binding.dpad_down": "十字键下",
		"ui.controller.binding.dpad_left": "十字键左",
		"ui.controller.binding.dpad_right": "十字键右",
		"ui.controller.binding.left_stick": "左摇杆按下",
		"ui.controller.binding.right_stick": "右摇杆按下",
		"ui.controller.binding.right_stick_vertical": "右摇杆上下",
		"ui.reconnect.title": "连接已断开",
		"ui.reconnect.reason_idle": "长时间未与服务器通信，请重连后继续。",
		"ui.reconnect.reason_unstable": "网络连接不稳定，请重连后继续。",
		"ui.reconnect.button": "重连",
		"ui.reconnect.connecting": "正在重连...",
		"ui.language.zh_cn": "简体中文",
		"ui.language.en": "English",
		"ui.button.back": "返回",
		"ui.today_decks.title": "今日卡组",
		"ui.today_decks.loading": "正在同步今日抽卡密匙",
		"ui.today_decks.no_key": "今日抽卡密匙尚未同步",
		"ui.today_decks.load_failed": "今日卡组同步失败：%s",
		"ui.today_decks.date": "密匙日期：%s",
		"ui.today_decks.reset_countdown": "密匙重置倒计时：%s",
		"ui.today_decks.empty_row": "%d. 未配置",
		"ui.today_decks.type.today": "今日新卡组",
		"ui.today_decks.type.yesterday": "昨日新卡组",
		"ui.today_decks.type.day_before": "前日新卡组",
		"ui.today_decks.type.random": "随机卡组",
		"ui.today_decks.visible_level": "可见等级：%d级",
		"ui.hand.page": "翻页",
		"ui.hand.synthesize": "合成",
		"ui.hand.discard": "丢弃",
		"ui.hand.store_vault": "存保险箱",
		"ui.nav.today_decks": "今日卡组",
		"ui.nav.card_pool": "抽卡",
		"ui.nav.vault": "保险箱",
		"ui.nav.deck_panel": "博物馆",
		"ui.nav.auction": "拍卖行",
		"ui.nav.ladder": "天梯榜",
		"ui.nav.mail": "邮箱",
		"ui.nav.settings": "设置",
		"ui.nav.exit_game": "退出游戏",
		"ui.nav.coming_soon": "%s · 敬请期待",
		"ui.exit_game.title": "退出游戏",
		"ui.exit_game.message": "确定要退出游戏吗？",
		"ui.exit_game.confirm": "确定退出",
		"ui.exit_game.cancel": "取消",
		"ui.exit_game.syncing": "正在保存并退出...",
		"ui.vault.title": "保险箱",
		"ui.vault.slot_count": "%d / %d 格",
		"ui.vault.organize": "整理保险箱",
		"ui.vault.unlock_gold": "金币扩展",
		"ui.vault.unlock_gold_cost": "本次费用：%d 金币",
		"ui.vault.unlock_gem": "宝石扩展",
		"ui.vault.unlock_gem_cost": "本次费用：%d 宝石",
		"ui.vault.unlock_cost_loading": "费用同步中",
		"ui.synthesis.title": "合成圣物 [选择5张同系列/同卡组/同色卡牌]",
		"ui.synthesis.button.count": "合成 (%d/5)",
		"ui.synthesis.button.valid": "合成 (5/5) ✓",
		"ui.synthesis.button.invalid": "合成 (5/5) ✗",
		"ui.synthesis.quick_select": "快速选择",
		"ui.synthesis.no_combo": "未找到可合成组合",
		"ui.synthesis.invalid_selected": "选中的卡牌不符合合成条件",
		"ui.synthesis.invalid_detail": "选中的卡牌不符合合成条件: 需要同系列、同卡组、同色、编号1-5",
		"ui.synthesis.crafting": "合成中...",
		"ui.synthesis.crafting_status": "正在合成...",
		"ui.synthesis.success_gold": "圣物合成成功! 奖励金币: %d",
		"ui.synthesis.done": "已合成",
		"ui.synthesis.failed": "合成失败: %s",
		"ui.synthesis.vault.count": "合成 (%d/5)",
		"ui.synthesis.vault.invalid": "合成 (%d/5)",
		"ui.synthesis.vault.valid": "合成 (5/5)",
		"ui.synthesis.vault.done": "合成成功",
		"ui.synthesis.vault.failed": "合成失败",
		"ui.deck_collection.title": "圣物博物馆",
		"ui.deck_collection.empty": "手动合成圣物后将在这里展示",
		"ui.deck_collection.color_header": "%s圣物",
		"ui.deck_collection.kind_count": " (%d 种)",
		"ui.deck_collection.relic_count": "已合成 %d 件",
		"ui.deck_collection.filter.colors_all": "稀有度：全部",
		"ui.deck_collection.filter.colors": "稀有度：%s",
		"ui.deck_collection.sort.recent": "最近获得时间",
		"ui.deck_collection.sort.oldest": "最远获得时间",
		"ui.deck_collection.sort.standard": "标准顺序",
		"ui.deck_collection.series_all": "全部系列",
		"ui.deck_collection.series_today_visible": "今日可见系列",
		"ui.deck_collection.progress": "已收藏 %d/%d",
		"ui.deck_collection.rarity.normal": "普通",
		"ui.deck_collection.rarity.excellent": "优秀",
		"ui.deck_collection.rarity.rare": "精良",
		"ui.deck_collection.rarity.epic": "史诗",
		"ui.deck_collection.rarity.legendary": "传说",
		"ui.deck_collection.rarity.ultimate": "究极",
		"ui.deck_collection.rarity.cosmic": "宇宙",
		"ui.level_up.title": "恭喜升到 %d 级",
		"ui.level_up.body": "星辉汇入你的收藏回路，新的探索权限已经点亮。",
		"ui.level_up.reward.gold": "金币 +%d",
		"ui.level_up.reward.gems": "宝石 +%d",
		"ui.level_up.reward.slot_hand": "手牌卡槽 +%d",
		"ui.level_up.reward.slot_pool": "卡池卡槽 +%d",
		"ui.level_up.reward.slot_vault": "保险箱卡槽 +%d",
		"ui.level_up.reward.stamina_cap": "体力上限 +%d",
		"ui.level_up.reward.stamina_full": "体力回满 %d/%d",
		"ui.level_up.reward.deck_visibility": "今日可见卡组范围已重新检查",
		"ui.level_up.dismiss": "点击任意处继续",
	},
	"en": {
		"ui.login.username": "Username",
		"ui.login.email": "Email",
		"ui.login.password": "Password",
		"ui.login.loading": "Loading...",
		"ui.login.syncing": "Syncing...",
		"ui.player.default_name": "Player",
		"ui.player.stats": "Lv.%d  Power %d",
		"ui.player.level_short": "Lv.%d",
		"ui.player.combat_power_short": "%d",
		"ui.color.white": "White",
		"ui.color.green": "Green",
		"ui.color.blue": "Blue",
		"ui.color.purple": "Purple",
		"ui.color.orange": "Orange",
		"ui.color.black": "Black",
		"ui.color.red": "Red",
		"error.draw.translating": "Could not translate the draw roll",
		"error.draw.reconciling": "Network instability detected; confirming the draw result",
		"error.draw.pending": "The previous draw is still being confirmed",
		"error.draw.no_stamina": "Not enough stamina",
		"error.card.not_in_pool": "This card is not in the current pool",
		"error.card.hand_full": "Your hand is full",
		"error.card.invalid_hand_slot": "Invalid hand slot",
		"error.card.not_in_hand_slot": "The card is not in this hand slot",
		"error.card.pool_full": "The card pool is full",
		"error.synthesis.need_five": "Exactly five cards are required",
		"error.synthesis.duplicate": "The same card cannot be selected twice",
		"error.synthesis.sync": "Could not sync card positions: %s",
		"ui.login.title.login": "Login",
		"ui.login.title.register": "Register",
		"ui.login.submit.login": "Login",
		"ui.login.submit.register": "Register",
		"ui.login.switch.to_register": "Create account",
		"ui.login.switch.to_login": "Back to login",
		"ui.login.exit_game": "Exit Game",
		"ui.login.error.missing_username_password": "Username and password are required",
		"ui.login.error.missing_email": "Email is required",
		"ui.login.country": "Nationality",
		"ui.login.country.hint": "Nationality (default: Earth)",
		"ui.login.prepare.title": "Login Preparation",
		"ui.login.prepare.waiting": "Waiting",
		"ui.login.prepare.failed": "Login preparation failed",
		"ui.login.prepare.done": "Ready. Entering main screen.",
		"ui.login.prepare.retry": "Retry",
		"ui.login.prepare.back": "Edit account",
		"ui.login.prepare.retry_hint": "Check the network or credentials and retry. Failed steps were written to the local log.",
		"ui.login.prepare.status.pending": "Pending",
		"ui.login.prepare.status.running": "Running",
		"ui.login.prepare.status.success": "✓ Done",
		"ui.login.prepare.status.failed": "Failed",
		"ui.login.prepare.step.init_local_config": "Init local config",
		"ui.login.prepare.step.check_client_version": "Check client version",
		"ui.login.prepare.step.load_local_token": "Load saved session",
		"ui.login.prepare.step.auth_refresh_or_login": "Verify or resume account",
		"ui.login.prepare.step.create_game_session": "Create game session",
		"ui.login.prepare.step.load_player_bootstrap": "Load player bootstrap",
		"ui.login.prepare.step.load_today_catalog": "Load today catalog",
		"ui.login.prepare.step.connect_realtime_or_heartbeat": "Connect online status",
		"ui.login.prepare.step.enter_main_menu": "Enter main menu",
		"ui.login.prepare.current.init_local_config": "Initializing local config",
		"ui.login.prepare.current.check_client_version": "Checking client version",
		"ui.login.prepare.current.load_local_token": "Loading saved session",
		"ui.login.prepare.current.auth_refresh_or_login": "Verifying account or resuming session",
		"ui.login.prepare.current.create_game_session": "Creating game session",
		"ui.login.prepare.current.load_player_bootstrap": "Loading player bootstrap",
		"ui.login.prepare.current.load_today_catalog": "Loading today catalog",
		"ui.login.prepare.current.connect_realtime_or_heartbeat": "Connecting online status",
		"ui.login.prepare.current.enter_main_menu": "Entering main menu",
		"ui.login.prepare.detail.session_saved": "Session saved",
		"ui.login.prepare.detail.background": "Continuing in background",
		"ui.login.prepare.detail.no_saved_session": "No saved session found",
		"ui.login.queue.waiting": "Server busy. Queue position %d. Estimated %d seconds.",
		"ui.login.queue.admitted": "Queue admitted. Entering.",
		"ui.login.queue.timeout": "Queue wait timed out. Please retry later.",
		"ui.login.loading.entering": "Entering Cosmic Card Realm",
		"ui.login.loading.collection": "Preparing collection space",
		"ui.login.loading.cards": "Organizing card pool and hand",
		"ui.login.loading.online": "Establishing game state",
		"ui.login.loading.done": "Ready",
		"ui.card_pool.refresh.free": "Stamina Draw",
		"ui.card_pool.refresh.free_newbie": "Gift %d",
		"ui.card_pool.refresh.free_regular": "Stamina %d",
		"ui.card_pool.refresh.next_free": "Next stamina %s",
		"ui.card_pool.refresh.cost_stamina": "Next cost: %d stamina",
		"ui.card_pool.refresh.cost_gold": "Next cost: %d gold",
		"ui.card_pool.refresh.cost_gem": "Next cost: %d gems",
		"ui.card_pool.refresh.gold": "Gold Draw",
		"ui.card_pool.refresh.gem": "Gem Draw",
		"ui.menu.title": "Settings",
		"ui.menu.music_volume": "Music",
		"ui.menu.sfx_volume": "SFX",
		"ui.menu.mute": "🔊 Mute",
		"ui.menu.muted": "🔇 Muted",
		"ui.menu.logout": "🚪 Logout",
		"ui.menu.language": "Language",
		"ui.menu.resolution": "Resolution",
		"ui.menu.window_mode": "Display Mode",
		"ui.menu.window_mode.fullscreen": "Fullscreen",
		"ui.menu.window_mode.windowed": "Windowed",
		"ui.settings.tab.basic": "Basic",
		"ui.settings.tab.controller": "Controls",
		"ui.settings.tab.profile": "Player Info",
		"ui.profile.title": "Player Information",
		"ui.profile.avatar": "Avatar",
		"ui.profile.avatar.change": "Change Avatar",
		"ui.profile.avatar.select": "Select an Unlocked Avatar",
		"ui.profile.region": "Region",
		"ui.profile.saving": "Saving…",
		"ui.profile.saved": "Saved",
		"ui.profile.save_failed": "Save failed. Please try again.",
		"ui.profile.avatar.north_star": "North Star Emblem",
		"ui.profile.avatar.moon_phase": "Moon Phase Emblem",
		"ui.profile.avatar.comet": "Comet Emblem",
		"ui.profile.avatar.armillary": "Armillary Sphere",
		"ui.profile.avatar.ostrich": "Ostrich Curator",
		"ui.profile.avatar.camel": "Camel Archivist",
		"ui.profile.avatar.bat": "Bat Observer",
		"ui.profile.avatar.lynx": "Lynx Appraiser",
		"ui.profile.avatar.magnifier": "Appraiser's Magnifier",
		"ui.profile.avatar.seal": "Archive Seal",
		"ui.profile.avatar.display_key": "Display Case Key",
		"ui.profile.avatar.astrolabe": "Astrolabe",
		"ui.controller.title": "Controller Bindings",
		"ui.controller.reset": "Reset Controller Defaults",
		"ui.controller.action.pointer_primary": "Left Click / Activate Focus",
		"ui.controller.action.pointer_secondary": "Right Click",
		"ui.controller.action.nav_prev": "Previous Nav Page",
		"ui.controller.action.nav_next": "Next Nav Page",
		"ui.controller.action.hand_page": "Hand Page",
		"ui.controller.action.draw_free": "Stamina / Free Draw",
		"ui.controller.action.synthesize": "Craft",
		"ui.controller.action.store_vault": "Store in Vault",
		"ui.controller.action.discard": "Discard",
		"ui.controller.action.draw_gem": "Gem Draw",
		"ui.controller.action.draw_gold": "Gold Draw",
		"ui.controller.binding.r2": "R2",
		"ui.controller.binding.l2": "L2",
		"ui.controller.binding.r1": "R1",
		"ui.controller.binding.l1": "L1",
		"ui.controller.binding.a": "A",
		"ui.controller.binding.b": "B",
		"ui.controller.binding.x": "X",
		"ui.controller.binding.y": "Y",
		"ui.controller.binding.dpad_up": "D-pad Up",
		"ui.controller.binding.dpad_down": "D-pad Down",
		"ui.controller.binding.dpad_left": "D-pad Left",
		"ui.controller.binding.dpad_right": "D-pad Right",
		"ui.controller.binding.left_stick": "Left Stick Press",
		"ui.controller.binding.right_stick": "Right Stick Press",
		"ui.controller.binding.right_stick_vertical": "Right Stick Up/Down",
		"ui.reconnect.title": "Connection Lost",
		"ui.reconnect.reason_idle": "The server connection was idle for too long. Reconnect to continue.",
		"ui.reconnect.reason_unstable": "The network connection is unstable. Reconnect to continue.",
		"ui.reconnect.button": "Reconnect",
		"ui.reconnect.connecting": "Reconnecting...",
		"ui.language.zh_cn": "简体中文",
		"ui.language.en": "English",
		"ui.button.back": "Back",
		"ui.today_decks.title": "Today's Decks",
		"ui.today_decks.loading": "Syncing today's draw key",
		"ui.today_decks.no_key": "Today's draw key has not synced yet",
		"ui.today_decks.load_failed": "Today's decks failed to sync: %s",
		"ui.today_decks.date": "Key date: %s",
		"ui.today_decks.reset_countdown": "Key reset: %s",
		"ui.today_decks.empty_row": "%d. Not configured",
		"ui.today_decks.type.today": "Today's New Deck",
		"ui.today_decks.type.yesterday": "Yesterday's New Deck",
		"ui.today_decks.type.day_before": "Previous New Deck",
		"ui.today_decks.type.random": "Random Deck",
		"ui.today_decks.visible_level": "Visible: Lv %d",
		"ui.hand.page": "Page",
		"ui.hand.synthesize": "Craft",
		"ui.hand.discard": "Discard",
		"ui.hand.store_vault": "Store",
		"ui.nav.today_decks": "Today",
		"ui.nav.card_pool": "Draw",
		"ui.nav.vault": "Vault",
		"ui.nav.deck_panel": "Museum",
		"ui.nav.auction": "Auction",
		"ui.nav.ladder": "Leaderboard",
		"ui.nav.mail": "Mail",
		"ui.nav.settings": "Settings",
		"ui.nav.exit_game": "Exit",
		"ui.nav.coming_soon": "%s · Soon",
		"ui.exit_game.title": "Exit Game",
		"ui.exit_game.message": "Exit the game?",
		"ui.exit_game.confirm": "Exit",
		"ui.exit_game.cancel": "Cancel",
		"ui.exit_game.syncing": "Saving and exiting...",
		"ui.vault.title": "Vault",
		"ui.vault.slot_count": "%d / %d slots",
		"ui.vault.organize": "Organize",
		"ui.vault.unlock_gold": "Gold Expand",
		"ui.vault.unlock_gold_cost": "Cost: %d gold",
		"ui.vault.unlock_gem": "Gem Expand",
		"ui.vault.unlock_gem_cost": "Cost: %d gems",
		"ui.vault.unlock_cost_loading": "Loading cost",
		"ui.synthesis.title": "Craft Relic [choose 5 matching cards]",
		"ui.synthesis.button.count": "Craft (%d/5)",
		"ui.synthesis.button.valid": "Craft (5/5) ✓",
		"ui.synthesis.button.invalid": "Craft (5/5) ✗",
		"ui.synthesis.quick_select": "Quick Select",
		"ui.synthesis.no_combo": "No craftable set found",
		"ui.synthesis.invalid_selected": "Selected cards cannot be crafted",
		"ui.synthesis.invalid_detail": "Selected cards must share series, deck, color, and numbers 1-5",
		"ui.synthesis.crafting": "Crafting...",
		"ui.synthesis.crafting_status": "Crafting...",
		"ui.synthesis.success_gold": "Relic crafted! Gold reward: %d",
		"ui.synthesis.done": "Crafted",
		"ui.synthesis.failed": "Craft failed: %s",
		"ui.synthesis.vault.count": "Craft (%d/5)",
		"ui.synthesis.vault.invalid": "Craft (%d/5)",
		"ui.synthesis.vault.valid": "Craft (5/5)",
		"ui.synthesis.vault.done": "Crafted",
		"ui.synthesis.vault.failed": "Craft Failed",
		"ui.deck_collection.title": "Relic Museum",
		"ui.deck_collection.empty": "Craft a relic to display it here",
		"ui.deck_collection.color_header": "%s Relics",
		"ui.deck_collection.kind_count": " (%d kinds)",
		"ui.deck_collection.relic_count": "Crafted x%d",
		"ui.deck_collection.filter.colors_all": "Rarity: All",
		"ui.deck_collection.filter.colors": "Rarity: %s",
		"ui.deck_collection.sort.recent": "Newest",
		"ui.deck_collection.sort.oldest": "Oldest",
		"ui.deck_collection.sort.standard": "Standard Order",
		"ui.deck_collection.series_all": "All Series",
		"ui.deck_collection.series_today_visible": "Today's Visible Series",
		"ui.deck_collection.progress": "Collected %d/%d",
		"ui.deck_collection.rarity.normal": "Common",
		"ui.deck_collection.rarity.excellent": "Uncommon",
		"ui.deck_collection.rarity.rare": "Rare",
		"ui.deck_collection.rarity.epic": "Epic",
		"ui.deck_collection.rarity.legendary": "Legendary",
		"ui.deck_collection.rarity.ultimate": "Ultimate",
		"ui.deck_collection.rarity.cosmic": "Cosmic",
		"ui.level_up.title": "Level %d Reached",
		"ui.level_up.body": "Starlight flows into your collection circuit. New exploration access has opened.",
		"ui.level_up.reward.gold": "Gold +%d",
		"ui.level_up.reward.gems": "Gems +%d",
		"ui.level_up.reward.slot_hand": "Hand slots +%d",
		"ui.level_up.reward.slot_pool": "Pool slots +%d",
		"ui.level_up.reward.slot_vault": "Vault slots +%d",
		"ui.level_up.reward.stamina_cap": "Stamina cap +%d",
		"ui.level_up.reward.stamina_full": "Stamina refilled %d/%d",
		"ui.level_up.reward.deck_visibility": "Today's visible deck range has been refreshed",
		"ui.level_up.dismiss": "Click anywhere to continue",
	},
}

func _ready() -> void:
	var saved_locale := str(Config.get_value("localization", "last_locale", DEFAULT_LOCALE))
	locale = saved_locale if saved_locale in SUPPORTED_LOCALES else DEFAULT_LOCALE

func set_locale(new_locale: String, persist_manual: bool = false, user_id: int = 0) -> void:
	if new_locale not in SUPPORTED_LOCALES:
		return
	var changed := locale != new_locale
	locale = new_locale
	Config.set_value("localization", "last_locale", locale)
	if persist_manual and user_id > 0:
		Config.set_value("localization", "user_%d" % user_id, locale)
	if changed:
		locale_changed.emit(locale)

func apply_account_default(country_code: String, user_id: int) -> void:
	var preference_key := "user_%d" % user_id
	var saved_preference := str(Config.get_value("localization", preference_key, ""))
	if saved_preference in SUPPORTED_LOCALES:
		set_locale(saved_preference)
		return
	set_locale("zh-CN" if country_code.to_upper() == "CN" else "en")

func get_http_locale() -> String:
	return locale

func t(key: String, params: Array = []) -> String:
	var table: Dictionary = _texts.get(locale, _texts[DEFAULT_LOCALE])
	var text := str(table.get(key, _texts[DEFAULT_LOCALE].get(key, key)))
	if params.size() > 0:
		return text % params
	return text
