extends Node

const DEFAULT_LOCALE := "zh-CN"

var locale: String = DEFAULT_LOCALE

var _texts := {
	"zh-CN": {
		"ui.login.username": "用户名",
		"ui.login.email": "邮箱",
		"ui.login.password": "密码",
		"ui.login.loading": "加载中...",
		"ui.login.syncing": "同步数据中...",
		"ui.login.title.login": "登录",
		"ui.login.title.register": "注册",
		"ui.login.submit.login": "登录",
		"ui.login.submit.register": "注册",
		"ui.login.switch.to_register": "没有账号？注册",
		"ui.login.switch.to_login": "已有账号？登录",
		"ui.login.error.missing_username_password": "用户名和密码不能为空",
		"ui.login.error.missing_email": "邮箱不能为空",
		"ui.login.prepare.title": "登录准备",
		"ui.login.prepare.waiting": "等待开始",
		"ui.login.prepare.failed": "登录准备失败",
		"ui.login.prepare.done": "准备完成，即将进入主界面",
		"ui.login.prepare.retry": "重试",
		"ui.login.prepare.back": "返回修改账号",
		"ui.login.prepare.retry_hint": "请检查网络或账号信息后重试。失败步骤已写入本地日志。",
		"ui.login.prepare.status.pending": "待处理",
		"ui.login.prepare.status.running": "进行中",
		"ui.login.prepare.status.success": "✓ 完成",
		"ui.login.prepare.status.failed": "失败",
		"ui.login.prepare.step.connect": "连接服务器",
		"ui.login.prepare.step.auth": "验证账号",
		"ui.login.prepare.step.session": "建立会话",
		"ui.login.prepare.step.profile": "加载玩家资料",
		"ui.login.prepare.step.config": "加载卡牌配置",
		"ui.login.prepare.step.collection": "同步收藏数据",
		"ui.login.prepare.step.daily": "检查每日奖励",
		"ui.login.prepare.step.ui": "准备主界面",
		"ui.login.prepare.current.connect": "正在连接服务器",
		"ui.login.prepare.current.auth": "正在验证账号",
		"ui.login.prepare.current.session": "正在建立会话并同步数据",
		"ui.login.prepare.current.ui": "正在准备主界面",
		"ui.login.prepare.detail.session_saved": "会话已保存",
		"ui.login.prepare.detail.background": "后台继续加载",
		"ui.card_pool.refresh.free": "🔄 免费刷新",
		"ui.card_pool.refresh.free_newbie": "🔄 新人免费 %d",
		"ui.card_pool.refresh.free_regular": "🔄 免费 %d",
		"ui.card_pool.refresh.next_free": "下次免费 %s",
		"ui.card_pool.refresh.gold": "💛 金币刷新",
		"ui.card_pool.refresh.gem": "💎 宝石刷新",
		"ui.menu.title": "菜单",
		"ui.menu.music_volume": "音乐音量",
		"ui.menu.sfx_volume": "音效音量",
		"ui.menu.mute": "🔊 静音",
		"ui.menu.muted": "🔇 已静音",
		"ui.menu.logout": "🚪 登出",
		"ui.button.back": "返回",
		"ui.hand.page": "◀▶ 翻页",
		"ui.hand.synthesize": "⚗ 合成",
		"ui.hand.discard": "🗑 丢弃",
		"ui.hand.store_vault": "📦 存保险箱",
		"ui.nav.card_pool": "抽卡",
		"ui.nav.vault": "保险箱",
		"ui.nav.deck_panel": "博物馆",
		"ui.nav.auction": "拍卖行",
		"ui.nav.ladder": "天梯榜",
		"ui.nav.mail": "邮箱",
		"ui.nav.coming_soon": "%s · 敬请期待",
		"ui.vault.title": "保险箱",
		"ui.vault.slot_count": "%d / %d 格",
		"ui.synthesis.title": "合成套牌 [选择5张同系列/同卡组/同色卡牌]",
		"ui.synthesis.button.count": "合成 (%d/5)",
		"ui.synthesis.button.valid": "合成 (5/5) ✓",
		"ui.synthesis.button.invalid": "合成 (5/5) ✗",
		"ui.synthesis.quick_select": "快速选择",
		"ui.synthesis.no_combo": "未找到可合成组合",
		"ui.synthesis.invalid_selected": "选中的卡牌不符合合成条件",
		"ui.synthesis.invalid_detail": "选中的卡牌不符合合成条件: 需要同系列、同卡组、同色、编号1-5",
		"ui.synthesis.crafting": "合成中...",
		"ui.synthesis.crafting_status": "正在合成...",
		"ui.synthesis.success_gold": "合成成功! 奖励金币: %d",
		"ui.synthesis.done": "已合成",
		"ui.synthesis.failed": "合成失败: %s",
		"ui.synthesis.vault.count": "✨ 合成 (%d/5)",
		"ui.synthesis.vault.invalid": "✨ 合成 (%d/5) ✗",
		"ui.synthesis.vault.valid": "✨ 合成 (5/5) ✓",
		"ui.synthesis.vault.done": "✅ 合成成功",
		"ui.synthesis.vault.failed": "❌ 合成失败",
		"ui.deck_collection.title": "🏆 已合成套牌",
		"ui.deck_collection.empty": "手动合成完整套牌后将在这里展示",
	},
	"en": {
		"ui.login.username": "Username",
		"ui.login.email": "Email",
		"ui.login.password": "Password",
		"ui.login.loading": "Loading...",
		"ui.login.syncing": "Syncing...",
		"ui.login.title.login": "Login",
		"ui.login.title.register": "Register",
		"ui.login.submit.login": "Login",
		"ui.login.submit.register": "Register",
		"ui.login.switch.to_register": "Create account",
		"ui.login.switch.to_login": "Back to login",
		"ui.login.error.missing_username_password": "Username and password are required",
		"ui.login.error.missing_email": "Email is required",
		"ui.login.prepare.title": "Login Preparation",
		"ui.login.prepare.waiting": "Waiting",
		"ui.login.prepare.failed": "Login preparation failed",
		"ui.login.prepare.done": "Ready. Entering main screen.",
		"ui.login.prepare.retry": "Retry",
		"ui.login.prepare.back": "Edit account",
		"ui.login.prepare.retry_hint": "Check the network or credentials and retry. Failed steps were written to the local log.",
		"ui.login.prepare.status.pending": "Pending",
		"ui.login.prepare.status.running": "Running",
		"ui.login.prepare.status.success": "✓ Done",
		"ui.login.prepare.status.failed": "Failed",
		"ui.login.prepare.step.connect": "Connect server",
		"ui.login.prepare.step.auth": "Verify account",
		"ui.login.prepare.step.session": "Create session",
		"ui.login.prepare.step.profile": "Load profile",
		"ui.login.prepare.step.config": "Load card config",
		"ui.login.prepare.step.collection": "Sync collection",
		"ui.login.prepare.step.daily": "Check daily reward",
		"ui.login.prepare.step.ui": "Prepare main UI",
		"ui.login.prepare.current.connect": "Connecting to server",
		"ui.login.prepare.current.auth": "Verifying account",
		"ui.login.prepare.current.session": "Creating session and syncing data",
		"ui.login.prepare.current.ui": "Preparing main UI",
		"ui.login.prepare.detail.session_saved": "Session saved",
		"ui.login.prepare.detail.background": "Continuing in background",
		"ui.card_pool.refresh.free": "🔄 Free",
		"ui.card_pool.refresh.free_newbie": "🔄 Newbie %d",
		"ui.card_pool.refresh.free_regular": "🔄 Free %d",
		"ui.card_pool.refresh.next_free": "Next free %s",
		"ui.card_pool.refresh.gold": "💛 Gold",
		"ui.card_pool.refresh.gem": "💎 Gems",
		"ui.menu.title": "Menu",
		"ui.menu.music_volume": "Music",
		"ui.menu.sfx_volume": "SFX",
		"ui.menu.mute": "🔊 Mute",
		"ui.menu.muted": "🔇 Muted",
		"ui.menu.logout": "🚪 Logout",
		"ui.button.back": "Back",
		"ui.hand.page": "◀▶ Page",
		"ui.hand.synthesize": "⚗ Craft",
		"ui.hand.discard": "🗑 Discard",
		"ui.hand.store_vault": "📦 Vault",
		"ui.nav.card_pool": "Draw",
		"ui.nav.vault": "Vault",
		"ui.nav.deck_panel": "Museum",
		"ui.nav.auction": "Auction",
		"ui.nav.ladder": "Leaderboard",
		"ui.nav.mail": "Mail",
		"ui.nav.coming_soon": "%s · Soon",
		"ui.vault.title": "Vault",
		"ui.vault.slot_count": "%d / %d slots",
		"ui.synthesis.title": "Craft Deck [choose 5 matching cards]",
		"ui.synthesis.button.count": "Craft (%d/5)",
		"ui.synthesis.button.valid": "Craft (5/5) ✓",
		"ui.synthesis.button.invalid": "Craft (5/5) ✗",
		"ui.synthesis.quick_select": "Quick Select",
		"ui.synthesis.no_combo": "No craftable set found",
		"ui.synthesis.invalid_selected": "Selected cards cannot be crafted",
		"ui.synthesis.invalid_detail": "Selected cards must share series, deck, color, and numbers 1-5",
		"ui.synthesis.crafting": "Crafting...",
		"ui.synthesis.crafting_status": "Crafting...",
		"ui.synthesis.success_gold": "Crafted! Gold reward: %d",
		"ui.synthesis.done": "Crafted",
		"ui.synthesis.failed": "Craft failed: %s",
		"ui.synthesis.vault.count": "✨ Craft (%d/5)",
		"ui.synthesis.vault.invalid": "✨ Craft (%d/5) ✗",
		"ui.synthesis.vault.valid": "✨ Craft (5/5) ✓",
		"ui.synthesis.vault.done": "✅ Crafted",
		"ui.synthesis.vault.failed": "❌ Craft Failed",
		"ui.deck_collection.title": "🏆 Crafted Decks",
		"ui.deck_collection.empty": "Craft a complete deck to display it here",
	},
}

func t(key: String, params: Array = []) -> String:
	var table: Dictionary = _texts.get(locale, _texts[DEFAULT_LOCALE])
	var text := str(table.get(key, _texts[DEFAULT_LOCALE].get(key, key)))
	if params.size() > 0:
		return text % params
	return text
